version: "3"
services:
  app:
      image: "node:14-alpine"
      working_dir: "/app"
      volumes:
        - ./todo-react-app/:/app
      ports:
        - "3000:3000"
      command: "yarn start"
      depends_on:
        - backend

  db:
    image: postgres
    volumes:
     - ./tmp/db:/var/lib/postgres/data
    environment:
      POSTGRES_USER: todo-api
      POSTGRES_PASSWORD: 123456

  backend:
    build:
      context: ./todo-rails-api
    volumes:
      - ./todo-rails-api:/todo-rails-api
    ports:
      - "3001:3001"
    depends_on:
      - db
